version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - nownabe
  assignees:
  - nownabe
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 3.9.8
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
